# Generated by Django 4.2.7 on 2023-11-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
